static_generator.py, templates/index.html, templates/page.html
This should give us something workable and nicer to demo.
=> Adding the index page and making the styles slightly nicer

dotastro8/meta4hack.yml
This is a PR auto-generated by a form to record hack "Meta^4hack"
=> Added entry for hack "Meta^4hack"

dotastro8/astrogoldstars.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 8 hack "AstroGoldStars"
=> Added entry for hack "AstroGoldStars"

dotastro6/cite-me-maybe.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 6 hack "Cite me maybe"
=> Added entry for hack "Cite me maybe"

dotastro8/markov-papers.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 8 hack "Markov Papers"
=> Added entry for hack "Markov Papers"

dotastro8/stellarautopsies.yml
=> Entry for Stellar Autopsies

dotastro5/python-client-for-the-nasa-ads-api.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 5 hack "Python client for the NASA ADS API"
=> Added entry for hack "Python client for the NASA ADS API"

dotastro8/".draft".yml
This is a PR auto-generated by a form to record information about the dotAstronomy 8 hack "".draft""
=> Added entry for hack "".draft""

dotastro8/project-apollo-stories.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 8 hack "Project Apollo Stories"
=> Added entry for hack "Project Apollo Stories"

site_generator/events.yml, validate_entries.py
=> Adding extra YAML config for listing page

site_generator/static_generator.py, site_generator/templates/index.html, site_generator/templates/page.html
For some strange reason all this code vanished from my previous PR...
=> Adding styles and content for home page

site_generator/static_generator.py, site_generator/templates/page.html
I noticed the images weren't appearing on the static page because they weren't being copied.  This should fix that. (and hopefully will just work right away if merged)
cc @zemogle
=> Fix image rendering on static page

dotastro8/spacebar.yml
=> Add Spacebar

dotastro9/README.md, events.yml
and updating the readme to have the description of the webpage rather than last year's
=> Adding dotastro9 to the webpage, too

Using_for_non_dotastro_meetings.md
First take on the list of todos for setting this up for something else than dotasto
=> readme for doing this for other meetings

dotastro9/whoseline.yml
With lots of help from others!
=> adding whoseline

dotastro8/xorastro-extremely-open,-extremely-reproducible-astronomy.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 8 hack "xorastro Extremely Open, Extremely Reproducible Astronomy"
=> Added entry for hack "xorastro Extremely Open, Extremely Reproducible Astronomy"

dotastro10/developing-social-justice-reading-groups-for-astronomical-communities.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 10 hack "Developing Social Justice Reading Groups for Astronomical Communities"
=> Added entry for hack "Developing Social Justice Reading Groups for Astronomical Communities"

dotastro10/public-outreach-tool-for-exploring-research-interactively.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 10 hack "Public outreach tool for exploring research interactively"
=> Added entry for hack "Public outreach tool for exploring research interactively"

dotastro10/data-sonification.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 10 hack "Data Sonification"
=> Added entry for hack "Data Sonification"

dotastro10/you-might-also-like-these-matplotlib-keywords.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 10 hack "You Might Also Like These Matplotlib Keywords"
=> Added entry for hack "You Might Also Like These Matplotlib Keywords"

dotastro10/specreduce-a-hack-day-package.yml
This is a PR auto-generated by a form to record information about the dotAstronomy 10 hack "Specreduce a hack day package"
=> Added entry for hack "Specreduce a hack day package"
